baseurl = "https://leonardohansa.com"
title = "Leonardo Hansa"
author = "Leonardo Hansa"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

GoogleAnalyticsID = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

summaryLength = 70

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Tu machine learning no sirve si no sabes explicarlo"
  dateform = "02/01/2006"
  title = "Leonardo Hansa"
  description = "Más cursos de data science no te quitarán el síndrome del impostor. Mejor base estadística, sí." 
  disableKinds = ["taxonomy", "taxonomyTerm"]
  
[[permalinks]]
    post = "/:year/:month/:day/:slug/"

  
[[menu.main]]
    name = "Correos"
    url = "/correos/"
    description = "Ejemplos de lo que te envío al correo"
    weight = 1
[[menu.main]]
    name = "Mediocre"
    url = "/soy-mediocre/"
    description = "Sobre mí"
    weight = 2
[[menu.main]]
    name = "Anti CV"
    url = "/anti-cv/"
    description = "Anti Curriculum Vitae"
    weight = 3

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
    
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

 [caches]
  [caches.images]
    dir = ':cacheDir/images'
